### ISSUE TITLE
ModuleNotFoundError: No module named 'ComfyUI-BlenderAI-node-1'

### ISSUE THREAD

**Issue by ManPython** [AIGODLIKE/ComfyUI-BlenderAI-node#108]
```
Traceback (most recent call last):
  File "E:\blender-3.6.5-windows-x64\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'ComfyUI-BlenderAI-node-1'
```

```
Traceback (most recent call last):
  File "E:\blender-4.1.1-windows-x64\4.1\scripts\modules\addon_utils.py", line 376, in enable
    mod = importlib.import_module(module_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\blender-4.1.1-windows-x64\4.1\python\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ComfyUI-BlenderAI-node-1'
```

https://github.com/ltdrdata/ComfyUI-Manager/issues/375

I think it is some dot problem around names
https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/commit/929adf90a38ae63bdb573028ad0d999c3e8ad16e

**Comment by jazzydog** [comment]
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'ComfyUI-BlenderAI-node-1'

some here

**Comment by KillyTheNetTerminal** [comment]
same error

**Comment by VRVirtuosos** [comment]
Same error in  b 4.1

**Comment by VRVirtuosos** [comment]
I fixed it by doing a Git clone of the repo.  It seems that the zip name needs to be ComfyUI-BlenderAI-node.zip  exactly if you want to use the zips
