### ISSUE TITLE
ComfyUI PINOKIO Crashed Blender

### ISSUE THREAD

**Issue by enzyme69** [AIGODLIKE/ComfyUI-BlenderAI-node#51]
I am using PINOKIO AI Browser - ComfyUI, and it crashes Blender. 

```
Error:
Saved session recovery to "/var/folders/dd/6tfdfc6x5pz37mrm2msqyc9r0000gn/T/quit.blend"
Writing userprefs: "/Users/jimmygunawan/Library/Application Support/Blender/3.6/config/userpref.blend" ok
Info: Preferences saved
Exception in module unregister(): '/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/BlenderGPT-main/__init__.py'
Traceback (most recent call last):
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 421, in disable
    mod.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/BlenderGPT-main/__init__.py", line 240, in unregister
    bpy.utils.unegister_class(GPT4_OT_DeleteMessage)
AttributeError: module 'bpy.utils' has no attribute 'unegister_class'
Unregistering Plasticity client
WARNING:bqt:unregistering bqt is not supported yet, skipping
Exception in module unregister(): '/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Sketch_N_Cage_1_0_4a_R.py'
Traceback (most recent call last):
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 421, in disable
    mod.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Sketch_N_Cage_1_0_4a_R.py", line 3992, in unregister
    bpy.utils.unregister_class(Draw_Mode)
RuntimeError: unregister_class(...):, missing bl_rna attribute from 'RNAMeta' instance (may not be registered)
Exception in module unregister(): '/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Sketch_N_Carve_4_2_0h_R.py'
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Sketch_N_Carve_4_2_0h_R.py", line 14450, in unregister
    bpy.types.VIEW3D_MT_draw_gpencil.remove(menu_func_a)
NameError: name 'menu_func_a' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/scripts/modules/addon_utils.py", line 421, in disable
    mod.unregister()
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/Sketch_N_Carve_4_2_0h_R.py", line 14452, in unregister
    bpy.types.VIEW3D_MT_paint_gpencil.remove(menu_func_a)
NameError: name 'menu_func_a' is not defined

Blender quit

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

```

**Comment by enzyme69** [comment]
That's because I assign Python path into venv or env?

**Comment by enzyme69** [comment]
If I don't point "python path" to venv,

Error:
```
WARNING:SDN:Server Launching
INFO:SDN:** ComfyUI start up time: 2023-12-22 07:19:11.353018
INFO:SDN:Prestartup times for custom nodes:
INFO:SDN:0.0 seconds: /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/rgthree-comfy
INFO:SDN:0.0 seconds: /Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/custom_nodes/ComfyUI-Manager
INFO:SDN:Total VRAM 32768 MB, total RAM 32768 MB
INFO:SDN:WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
INFO:SDN:PyTorch 2.0.0 with CUDA None (you have 2.1.0)
INFO:SDN:Python  3.10.9 (you have 3.10.13)
INFO:SDN:Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
INFO:SDN:Memory-efficient attention, SwiGLU, sparse and more won't be available.
INFO:SDN:Set XFORMERS_MORE_DETAILS=1 for more details
INFO:SDN:xformers version: 0.0.20
INFO:SDN:Traceback (most recent call last):
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy/model_management.py", line 218, in <module>
INFO:SDN:import accelerate
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/__init__.py", line 3, in <module>
INFO:SDN:from .accelerator import Accelerator
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/accelerator.py", line 35, in <module>
INFO:SDN:from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/checkpointing.py", line 24, in <module>
INFO:SDN:from .utils import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/utils/__init__.py", line 159, in <module>
INFO:SDN:from .megatron_lm import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/accelerate/utils/megatron_lm.py", line 32, in <module>
INFO:SDN:from transformers.modeling_outputs import (
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
INFO:SDN:from . import dependency_versions_check
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
INFO:SDN:require_version_core(deps[pkg])
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
INFO:SDN:return require_version(requirement, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
INFO:SDN:_compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
INFO:SDN:raise ImportError(
INFO:SDN:ImportError: huggingface-hub>=0.19.3,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.0.
INFO:SDN:Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
INFO:SDN:ERROR: LOW VRAM MODE NEEDS accelerate.
INFO:SDN:Set vram state to: SHARED
INFO:SDN:Device: mps
INFO:SDN:VAE dtype: torch.float32
INFO:SDN:Traceback (most recent call last):
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/main.py", line 72, in <module>
INFO:SDN:import execution
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/execution.py", line 12, in <module>
INFO:SDN:import nodes
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/nodes.py", line 20, in <module>
INFO:SDN:import comfy.diffusers_load
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy/diffusers_load.py", line 4, in <module>
INFO:SDN:import comfy.sd
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy/sd.py", line 12, in <module>
INFO:SDN:from . import clip_vision
INFO:SDN:File "/Users/jimmygunawan/pinokio/api/comfyui.pinokio.git/ComfyUI/comfy/clip_vision.py", line 1, in <module>
INFO:SDN:from transformers import CLIPVisionModelWithProjection, CLIPVisionConfig, modeling_utils
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/__init__.py", line 26, in <module>
INFO:SDN:from . import dependency_versions_check
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 57, in <module>
INFO:SDN:require_version_core(deps[pkg])
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 117, in require_version_core
INFO:SDN:return require_version(requirement, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 111, in require_version
INFO:SDN:_compare_versions(op, got_ver, want_ver, requirement, pkg, hint)
INFO:SDN:File "/Users/jimmygunawan/miniconda3/lib/python3.10/site-packages/transformers/utils/versions.py", line 44, in _compare_versions
INFO:SDN:raise ImportError(
INFO:SDN:ImportError: huggingface-hub>=0.19.3,<1.0 is required for a normal functioning of this module, but found huggingface-hub==0.19.0.
INFO:SDN:Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
DEBUG:SDN:STDOUT Listen Thread Exit
ERROR:SDN:Server Launch Failed
INFO:SDN:Launch Time: 1.87s
WARNING:SDN:Parsing Node Start
WARNING:SDN:Parsing Node Finished!
INFO:SDN:ParseNode Time: 0.00s
INFO:SDN:RegNode Time: 0.01s
```

**Comment by KarryCharon** [comment]
@enzyme69 On unix-like platform the python env is more complicated than windows.If python path is not set the `python3` is used for launching the ComfyUI. And python env is not an aspect that plugin need to pay attention to, so you need to prepare a python that can run ComfyUI normally.
