### ISSUE TITLE
ComfyUI Remote Server works but the issue is with Multiline Text Input Prompt

### ISSUE THREAD

**Issue by enzyme69** [AIGODLIKE/ComfyUI-BlenderAI-node#53]
I cannot get a simple text / multiline text node for CLIP encode prompt to work...

```
Collecting imgui
  Downloading https://mirrors.aliyun.com/pypi/packages/f1/aa/4abb0d3d6054da9a4390160fc25ca743a824263a9931cc6a95f30e3d75b4/imgui-2.0.0.tar.gz (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 481.1 kB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: imgui
  Building wheel for imgui (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for imgui (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11.00-arm64-cpython-310
      creating build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/extra.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/__init__.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/_compat.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      creating build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/glumpy.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/sdl2.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/__init__.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/opengl.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/pygame.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/cocos2d.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/pyglet.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/base.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      copying imgui/integrations/glfw.py -> build/lib.macosx-11.00-arm64-cpython-310/imgui/integrations
      running egg_info
      writing imgui.egg-info/PKG-INFO
      writing dependency_links to imgui.egg-info/dependency_links.txt
      writing requirements to imgui.egg-info/requires.txt
      writing top-level names to imgui.egg-info/top_level.txt
      reading manifest file 'imgui.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'imgui-cpp/examples'
      no previously-included directories found matching 'imgui-cpp/extra_fonts'
      adding license file 'LICENSE'
      writing manifest file 'imgui.egg-info/SOURCES.txt'
      copying imgui/ansifeed.pxd -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/cimgui.pxd -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/common.pyx -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/core.cpp -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/core.h -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/core.pxd -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/core.pyx -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/enums.pxd -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/enums_internal.pxd -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/internal.cpp -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/internal.h -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/internal.pxd -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      copying imgui/internal.pyx -> build/lib.macosx-11.00-arm64-cpython-310/imgui
      running build_ext
      building 'imgui.core' extension
      creating build/temp.macosx-11.00-arm64-cpython-310
      creating build/temp.macosx-11.00-arm64-cpython-310/config-cpp
      creating build/temp.macosx-11.00-arm64-cpython-310/imgui-cpp
      creating build/temp.macosx-11.00-arm64-cpython-310/imgui
      gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Users/brecht/dev/build_darwin/deps/Release/sqlite/include -I/Users/brecht/dev/build_darwin/deps/Release/bzip2/include -I/Users/brecht/dev/build_darwin/deps/Release/lzma/include -I/Users/brecht/dev/build_darwin/deps/Release/zlib/include -mmacosx-version-min=11.00 -arch arm64 -mmacosx-version-min=11.00 -arch arm64 -DPYIMGUI_CUSTOM_EXCEPTION -Iimgui-cpp -Iansifeed-cpp -I./imgui -Iimgui -Iconfig-cpp "-I/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/python/include/python3.10" -c config-cpp/py_imconfig.cpp -o build/temp.macosx-11.00-arm64-cpython-310/config-cpp/py_imconfig.o -includeconfig-cpp/py_imconfig.h
      In file included from <built-in>:1:
      ./config-cpp/py_imconfig.h:14:10: fatal error: 'Python.h' file not found
      #include <Python.h>
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for imgui
Failed to build imgui
ERROR: Could not build wheels for imgui, which is required to install pyproject.toml-based projects
Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/MultiLineText/__init__.py", line 41, in execute
    bpy.ops.sdn.multiline_text("INVOKE_DEFAULT")
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
AttributeError: Calling operator "bpy.ops.sdn.multiline_text" error, could not be found
Error: MultiLineText Not Enabled
Error: Python: Traceback (most recent call last):
  File "/Users/jimmygunawan/Library/Application Support/Blender/3.6/scripts/addons/ComfyUI-BlenderAI-node-develop/MultiLineText/__init__.py", line 41, in execute
    bpy.ops.sdn.multiline_text("INVOKE_DEFAULT")
  File "/Applications/Blender 36 LTS/Blender.app/Contents/Resources/3.6/scripts/modules/bpy/ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
AttributeError: Calling operator "bpy.ops.sdn.multiline_text" error, could not be found

```

**Comment by KarryCharon** [comment]
@enzyme69 May caused by the pip install imgui. We had changed the pip install solution to binary prefer.
