### ISSUE TITLE
Issue when loading Lora and AnimateDiff SDXL and Stable Diffusion v1.5 models

### ISSUE THREAD

**Issue by gioxyer** [AIGODLIKE/ComfyUI-BlenderAI-node#84]
Issue when loading Lora and AnimateDiff SDXL and Stable Diffusion v1.5 models
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/304365d7-1c99-40fc-aede-b32f8f0baa10)

Model installed on **"ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-main\models"**
- animatediffMotion_sdxlV10Beta.ckpt
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/323ca18c-4698-430b-a273-bc3459aa5916)

Model installed on **"ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-main\loras"**
- mm_sd_v15_v2.ckpt
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/ebe17ab9-9635-4415-9bf1-f5acdb3ceb7e)

**CMD with ComfyUI:**
C:\Users\giorg\Downloads\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --cpu --windows-standalone-build
Total VRAM 15694 MB, total RAM 15694 MB
Set vram state to: DISABLED
Device: cpu
VAE dtype: torch.float32
Using sub quadratic optimization for cross attention, if you have memory or speed issues try using: --use-split-cross-attention
Traceback (most recent call last):
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\giorg\\Downloads\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CUP\\__init__.py'

Cannot import C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CUP module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\giorg\\Downloads\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-CUP\\__init__.py'
Config Export Error[Errno 2] No such file or directory: 'XXXHOST-PATHXXX\\PATH_CFG.json'Traceback (most recent call last):
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\giorg\\Downloads\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\sd-webui-animatediff-master\\__init__.py'

Cannot import C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-webui-animatediff-master module for custom nodes: [Errno 2] No such file or directory: 'C:\\Users\\giorg\\Downloads\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\sd-webui-animatediff-master\\__init__.py'

Import times for custom nodes:
   0.0 seconds: C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\Cup-ClipBoard
   0.0 seconds (IMPORT FAILED): C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CUP
   0.0 seconds (IMPORT FAILED): C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\sd-webui-animatediff-master
   0.0 seconds: C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-CUP-main
   0.0 seconds: C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-main

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
[AnimateDiff] - INFO - Loading lora mm_sd_v15_v2.ckpt
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-main\animatediff\nodes.py", line 120, in load_lora
    lora = load_lora(lora_name)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-main\animatediff\model_utils.py", line 96, in load_lora
    updated_state_dict[combined_key] = torch.mm(weight_up, weight_down).to("cpu")
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: self must be a matrix

Prompt executed in 3.72 seconds

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/4a5b61fa-0df8-48cd-a2c7-25b379bc1a78)

**CMD on ComfyUI Blender AddOn**
Read prefs: "C:\Users\giorg\AppData\Roaming\Blender Foundation\Blender\4.1\config\userpref.blend"
"nvidia-smi" non è riconosciuto come comando interno o esterno,
 un programma eseguibile o un file batch.
[SDN-INF]: Launch Time: 0.00s
[SDN-INF]: UnregNode Time: 0.00s
register_class(...):
Warning: 'MLTWords_UL_UIList' doesn't have upper case alpha-numeric prefix
register_class(...):
Warning: 'MLTText_UL_UIList' doesn't have upper case alpha-numeric prefix
[SDN-WRN]: Parsing Node Start
[SDN-WRN]: Parsing Node Finished!
[SDN-INF]: ParseNode Time: 0.21s
[SDN-INF]: RegNode Time: 0.46s
BlenderAI_Node Launch Time: 3.3228s
BlenderAI_Node Register cost 0.5079s
humgen3d addon: Verbose is enabled
humgen3d addon: Read in JSON settings from file
Warning: addon-module rigify found module but without '__addon_enabled__' field, possible name collision from file: 'C:\\Program Files\\Blender Foundation\\Blender 4.1\\4.1\\scripts\\addons\\rigify\\__init__.py'
[SDN-INF]: Load MLT Words: 1.0559s
HG_INFO:         Activating HumGen, version (4, 0, 14)
Read blend: "C:\Users\giorg\Downloads\AItest v2.blend"
[SDN-INF]: Load MLT Words: 1.0254s
HG_INFO:         Activating HumGen, version (4, 0, 14)
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'AnimateDiffLoraLoader', 'AnimateDiffLoraLoader', 'lora_name'

[SDN-WRN]: Server Launched
[SDN-INF]: Launch Time: 0.05s
[SDN-INF]: UnregNode Time: 0.00s
register_class(...):
Warning: 'MLTWords_UL_UIList' doesn't have upper case alpha-numeric prefix
register_class(...):
Warning: 'MLTText_UL_UIList' doesn't have upper case alpha-numeric prefix
[SDN-WRN]: Parsing Node Start
[SDN-WRN]: Parsing Node Finished!
[SDN-INF]: ParseNode Time: 0.20s
[SDN-INF]: RegNode Time: 0.33s
[SDN-DBG]: Add Task
[SDN-DBG]: Submit Task
[SDN-WRN]: Render->C:/Users/giorg/AppData/Local/Temp/viewport.png
Saved: 'C:\Users\giorg\AppData\Local\Temp\viewport.png'
OpenGL Render written to 'C:\Users\giorg\AppData\Local\Temp\viewport.png'
[SDN-INF]: Upload Image Success
[SDN-DBG]: P/R: 0/0
[SDN-DBG]: Execution Cached: []
[SDN-DBG]: Executing Node: 7
[SDN-ERR]:
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-main\animatediff\nodes.py", line 120, in load_lora
    lora = load_lora(lora_name)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\giorg\Downloads\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff-main\animatediff\model_utils.py", line 96, in load_lora
    updated_state_dict[combined_key] = torch.mm(weight_up, weight_down).to("cpu")
                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
WARN (bpy.rna): C:\Users\blender\git\blender-v410\blender.git\source\blender\python\intern\bpy_rna.cc:1366 pyrna_enum_to_py: current value '0' matches no enum in 'AnimateDiffLoraLoader', 'AnimateDiffLoraLoader', 'lora_name'

[SDN-ERR]: self must be a matrix
[SDN-ERR]: Node Error Parse
Node:7
{'type': 'RuntimeError', 'message': 'self must be a matrix'}
Info: Saved "AItest v2.blend"

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/c2434a40-e5bc-4750-8a99-cd034cad5dfb)

Models installed in custom_nodes:
- sd-webui-animatediff-master
- comfyui-animatediff-main

![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/9a47c1a7-57dd-4b8c-8df7-c075a33c3e58)

**Comment by gioxyer** [comment]
I find the issue, but how to save the final animation?
![image](https://github.com/AIGODLIKE/ComfyUI-BlenderAI-node/assets/161426313/3b30f167-cc58-4862-a662-98955a60a469)

**Comment by gioxyer** [comment]
Fixed, I find the folder in output in ComfyUI
